-- ===============================================================
-- Supabase Setup Script for Port Sudan AI App
-- ===============================================================
-- This script will drop existing tables and recreate the entire schema.
-- Copy and paste this into the Supabase SQL Editor.

-- 1. Drop existing tables (if they exist)
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS ai_logs CASCADE;
DROP TABLE IF EXISTS forum_posts CASCADE;
DROP TABLE IF EXISTS ads CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS neighborhoods CASCADE;
DROP TABLE IF EXISTS professions CASCADE;

-- 2. Create Profiles Table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  fullName TEXT,
  avatar_url TEXT,
  points INTEGER DEFAULT 150,
  role TEXT DEFAULT 'user',
  is_verified BOOLEAN DEFAULT false,
  gemini_api_key TEXT,
  ai_usage_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create Neighborhoods Table
CREATE TABLE neighborhoods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create Professions Table
CREATE TABLE professions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Create Ads Table
CREATE TABLE ads (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  profession TEXT NOT NULL,
  neighborhood TEXT NOT NULL,
  phone TEXT NOT NULL,
  type TEXT CHECK (type IN ('offer', 'request')),
  is_premium BOOLEAN DEFAULT false,
  is_productive_family BOOLEAN DEFAULT false,
  is_training BOOLEAN DEFAULT false,
  image_url TEXT,
  status TEXT DEFAULT 'approved',
  avg_rating DECIMAL(3,2) DEFAULT 0.00,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Create Forum Posts Table
CREATE TABLE forum_posts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Create Ratings Table
CREATE TABLE ratings (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  ad_id UUID REFERENCES ads(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Create AI Logs Table
CREATE TABLE ai_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  feature TEXT NOT NULL,
  prompt TEXT,
  response TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE ads ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE neighborhoods ENABLE ROW LEVEL SECURITY;
ALTER TABLE professions ENABLE ROW LEVEL SECURITY;

-- 10. RLS Policies

-- Profiles: Users can read all profiles, but only update their own
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Ads: Everyone can read approved ads, users can insert/update/delete their own
CREATE POLICY "Approved ads are viewable by everyone" ON ads FOR SELECT USING (status = 'approved');
CREATE POLICY "Users can insert their own ads" ON ads FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own ads" ON ads FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own ads" ON ads FOR DELETE USING (auth.uid() = user_id);

-- Forum Posts: Everyone can read, users can insert their own
CREATE POLICY "Forum posts are viewable by everyone" ON forum_posts FOR SELECT USING (true);
CREATE POLICY "Users can insert their own forum posts" ON forum_posts FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Ratings: Everyone can read, users can insert their own
CREATE POLICY "Ratings are viewable by everyone" ON ratings FOR SELECT USING (true);
CREATE POLICY "Users can insert their own ratings" ON ratings FOR INSERT WITH CHECK (auth.uid() = user_id);

-- AI Logs: Users can only see their own logs
CREATE POLICY "Users can view own AI logs" ON ai_logs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own AI logs" ON ai_logs FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Neighborhoods & Professions: Read-only for everyone
CREATE POLICY "Neighborhoods are viewable by everyone" ON neighborhoods FOR SELECT USING (true);
CREATE POLICY "Professions are viewable by everyone" ON professions FOR SELECT USING (true);

-- 11. Triggers and Functions

-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, fullName, avatar_url, points, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'fullName', 'مستخدم جديد'),
    COALESCE(NEW.raw_user_meta_data->>'avatar_url', 'https://api.dicebear.com/7.x/avataaars/svg?seed=' || NEW.id),
    150,
    'user'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for new user signup
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Function to update ad average rating
CREATE OR REPLACE FUNCTION update_ad_avg_rating()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE ads
  SET avg_rating = (
    SELECT AVG(rating)::DECIMAL(3,2)
    FROM ratings
    WHERE ad_id = NEW.ad_id
  )
  WHERE id = NEW.ad_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for updating average rating
CREATE TRIGGER on_rating_inserted
  AFTER INSERT ON ratings
  FOR EACH ROW EXECUTE FUNCTION update_ad_avg_rating();

-- 12. Populate Neighborhoods
INSERT INTO neighborhoods (name) VALUES
('ديم مايو'), ('ديم النور'), ('هدل'), ('حي الخليج'), ('الثورة'), ('سلبونا'), ('سلالاب'), ('الإسكان'), ('شقر'), ('الوحدة'),
('الإسكندرية'), ('أم القرى'), ('ولع'), ('حي الأغاريق'), ('حي العظمة'), ('سكة حديد'), ('ديم مدينة'), ('ديم عرب'),
('حي الشاطئ'), ('ديم سواكن'), ('ديم حجر'), ('كوريا'), ('ترانسيت'), ('دار السلام'), ('حي الجنائن'), ('دار النعيم'),
('الرياض'), ('المرغنية'), ('فلب'),
('حي المطار مربع 1'), ('حي المطار مربع 2'), ('حي المطار مربع 3'), ('حي المطار مربع 4'), ('حي المطار مربع 5'),
('حي المطار مربع 6'), ('حي المطار مربع 7'), ('حي المطار مربع 8'), ('حي المطار مربع 9'), ('حي المطار مربع 10'),
('حي المطار مربع 11'), ('حي المطار مربع 12'), ('حي المطار مربع 13'), ('حي المطار مربع 14'), ('حي المطار مربع 15'),
('حي المطار مربع 16'), ('حي المطار مربع 17'), ('حي المطار مربع 18'), ('حي المطار مربع 19'), ('حي المطار مربع 20'),
('حي المطار مربع 21'), ('حي المطار مربع 22'), ('حي المطار مربع 23'), ('حي المطار مربع 24'), ('حي المطار مربع 25'),
('حي المطار مربع 26'), ('حي المطار مربع 27'), ('حي المطار مربع 28'), ('حي المطار مربع 29'), ('حي المطار مربع 30'),
('حي المطار مربع 31'), ('حي المطار مربع 32'), ('حي المطار مربع 33'), ('حي المطار مربع 34'), ('حي المطار مربع 35'),
('حي المطار مربع 36');

-- 13. Populate Professions
INSERT INTO professions (name) VALUES
('كهرباء مباني'), ('كهرباء سيارات'), ('فني طاقة شمسية'), ('فني كاميرات مراقبة'), ('فني إنذار حريق'),
('فني تمديدات كهربائية صناعية'), ('إصلاح أجهزة منزلية'), ('فني تكييف وتبريد'), ('فني غسالات'),
('فني ثلاجات'), ('فني أفران'), ('فني مصاعد'), ('نجار أثاث'), ('نجار أبواب'), ('نجار مطابخ'), ('نجار مسلح'),
('حداد أبواب وشبابيك'), ('حداد مظلات'), ('حداد سمكرة سيارات'), ('لحام كهرباء'), ('لحام أرجون'),
('ميكانيكي سيارات'), ('ميكانيكي ديزل'), ('ميكانيكي ركشات'), ('ميكانيكي مواتر'), ('ميكانيكي شاحنات'),
('فني تغيير زيوت'), ('فني بطاريات سيارات'), ('فني إطارات'), ('بناء'), ('سباك'), ('نقاش ودهانات'),
('مركب بلاط'), ('مركب سيراميك'), ('مركب رخام'), ('عامل محارة'), ('عامل جبص'), ('فني ألمنيوم'), ('فني زجاج'),
('سائق ركشة'), ('سائق أمجاد'), ('سائق حافلة'), ('سائق شاحنة'), ('دليفري مطاعم'), ('دليفري أدوية'),
('توصيل طرود'), ('نقل عفش'), ('نقل مواد بناء'), ('سمسار عقارات'), ('سمسار سيارات'), ('بائع مواد بناء'),
('بائع أدوات كهربائية'), ('بائع أجهزة إلكترونية'), ('بائع ملابس'), ('بائع عطور'), ('بائع خضروات'),
('بائع لحوم'), ('بائع موبايلات'), ('مخلص جمركي'), ('وكيل شحن'), ('عامل شحن وتفريغ'), ('عتالة ميناء'),
('مراقب مخازن'), ('عامل نظافة'), ('حارس أمن'), ('طباخ'), ('مساعد طباخ'), ('عامل تقديم'), ('مصور فوتوغرافي'),
('مصور فيديو'), ('مصمم جرافيك'), ('محرر فيديو'), ('كاتب محتوى'), ('مبرمج مواقع'), ('مبرمج تطبيقات'),
('مدير صفحات سوشيال ميديا'), ('مسوق إلكتروني'), ('فني شبكات'), ('فني صيانة كمبيوتر'), ('فني صيانة موبايلات'),
('حلاق رجالي'), ('كوافير نسائي'), ('خبير تجميل'), ('فني مساج'), ('ممرض منزلي'), ('مدرس خصوصي'),
('مدرب لياقة بدنية'), ('مدرب قيادة سيارات'), ('فني أجهزة طبية'), ('مزارع'), ('صياد'), ('محاسب'), ('أمين صندوق');
